### ISSUE TITLE
Desired slidesPresented implementation

### ISSUE THREAD

**Issue by wwwhatley** [FlorianRappl/react-carousel-hook-example#1]
![Mar-08-2020 11-54-01](https://user-images.githubusercontent.com/30512540/76168257-95a3fc80-6133-11ea-8a16-476ef16246cd.gif)

**Comment by FlorianRappl** [comment]
I think the effect could be nicer, but in any case I've extended the implementation to support multiple slides presented.

Hope that helps!

**Comment by wwwhatley** [comment]
This is incredible! Thanks so much @FlorianRappl  - the only issue I'm having is the way the slide jumps from one to another, there is a lag... I'm sorry to ask you so many questions, but do you know what may be causing this? Having a hard time figuring it out.

**Comment by FlorianRappl** [comment]
> I'm sorry to ask you so many questions, but do you know what may be causing this?

My assumption: The CSS transition would need some adjustment here. Another thought: The drag handling is not ideal.

If you want the picture above realized (i.e., using buttons) then it *should* feel more smooth. Not really sure though.

Maybe I'll find the time to revisit it, but this week is already quite packed.

PS: If you are interested in microfrontends or maybe are in the future - make sure to [star Piral :star:](https://github.com/smapiot/piral). Much appreciated!

**Comment by wwwhatley** [comment]
No worries, understood. For now, I don't need the drag functionality, but any ideas of where to start to see how it can transition from slide to slide without jumping?

![Mar-09-2020 13-35-56](https://user-images.githubusercontent.com/30512540/76250420-f3efde80-620a-11ea-9ddc-3293b4bda771.gif)

**Comment by nghinton** [comment]
@wwwhatley I was able to fix the jumping by multiplying the quotient of the shift calculation by the number of slides presented
